---
title: "An Association Rules Based Method for Imputing Missing Ordinal and Likert Scale Data"
author: "A dissertation by Julian Hatwell for the Master of Science degree in Business Intelligence at Birmingham City University, faculty of Computing, Engineering and the Built Environment"
date: "September 2017"
site: bookdown::bookdown_site
# geometry: [left=40mm, right=25mm, top=25mm, bottom=25mm] # [a4paper] 
geometry: [margin=0.984in, a4paper]
fontsize: 12pt
mainfont: helvetica
colorlinks: true
documentclass: book
output: 
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    toc_depth: 3
    toc_appendix: yes
    citation_package: biblatex
    template: C:\Dev\Prog\R-3.4.0\library\rmarkdown\rmd\latex\BCUcustom.tex
clean: [packages.bib, bookdown.bbl]
bibliography: [likertimputebiblio.bib, packages.bib]
biblio-style: authoryear
biblatexoptions: [maxcitenames=2]
csl: harvard-university-of-wolverhampton.csl
link-citations: true
nocite: | 
  @R-bookdown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE
                      , message = FALSE
                      , warning = FALSE)

options(xtable.comment = FALSE)

# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr'
  , 'rmarkdown', 'lattice'
  , 'arules', 'arulesViz'
  , 'missForest', 'mi'
  , 'Amelia', 'VIM'
  , 'mice', 'arulesCBA'
  , 'psych', 'cocor'
  , 'lavaan', 'Zelig'
  , 'ordPens', 'ordinal'
  , 'Hmisc', 'HDInterval'
), 'packages.bib')
library(xtable)
library(lattice)
library(latticeExtra)
library(ggplot2)
library(arulesimp)
library(psych)
library(VIM)
library(Amelia)
library(Zelig)
library(mice)
library(arulesCBA)
library(pander)
source("C:\\Dev\\Study\\R\\R_Themes\\MarketingTheme.R")
source("run_experiments_header.R")
source("synth_wu_data.R")
```

# List of Abbreviations {-}

AR - Association Rule(s)\newline
ARM - Association Rules Mining\newline
CBA - Classification Based on Associations\newline
CMAR - Classification based on Multiple Association Rules\newline
EM - Expectation Maximization\newline
EMB - Expectation Maximization with Bootstrapping\newline
FIML - Full Information Maximum Likelihood\newline
FMI - Fraction of Missing Information\newline
HDI - Higher Density Interval\newline
IM - Item Mean\newline
KNN - K-Nearest Neighbours\newline
MASE - Mean Absolute Scale Error\newline
MCMC - Monte Carlo Markov Chain\newline
MCAR - Missing Completely at Random\newline
MAR - Missing at Random\newline
MNAR - Missing not at Random\newline
MI - Multiple Imputation\newline
MICE - Multiple Imputation with Chained Equations\newline
PM - Person Mean\newline
PIM - Person Item Mean\newline
PMM - Predictive Mean Matching\newline
RLRT - Restricted Likelihood Ratio Test\newline
SEM - Structural Equation Model\newline
SPRM - Similar Pattern Response Matching\newline
SSE - Scale Score Error\newline


# Acknowledgements {-}

With special thanks to my supervisor, Professor Mohamed Medhat Gaber for guidance during this project.\newline

To my mother, without whom none of this would be possible.\newline

To Daniel, "you are a positive, motivating force within my life."\newline

OxIS 2013 databases provided by the Oxford Internet Institute on 21/04/2017.\newline

Job Satisfaction and Procedural Fairness data provided by Prof. Maurizio Carpita.

# Abstract {-}

**this will have to change once the research method and resutls come through**

Surveys are an ubiquitous research tool, used in the widest variety of disciplines. The data collected mainly includes categorical types (binary, nominal, ordinal and Likert). Due to the practicalities of running surveys, they are highly prone to non-response and therefore, missing data. The magnitude, pattern and distribution of missingness depends on the underlying cause and has consequences for the analysis of results. These problems include serious loss of statistical power and biased parameter estimates. There are many techniques to recover the analysis with varying degrees of success. Most important of these is imputation, which is to substitute  missing values with suitable or "plausible" values. Successful imputation depends on the features of the data and the characteristics of missingness. Techniques are very well developed for continuous, numerical data but much less so for caterogical types where there are still gaps in the literature.

Since association rules mining (ARM) was proposed, the concept has been the subject of intense research. ARM is best suited to applications on categorical data. While the technique is inherently a descriptive, knowledge discovery tool, it has been successfully adapted for classification but never used for imputation. This project proposes a novel technique based on ARM for the imputation of categorical data, especially ordinal and Likert scales. A simulation experiment is used to benchmark the novel technique against popular and state of the art methods.